module.exports = {
  inputFiles: ['./src'],
  exclude: '**/*.test.ts',
  mode: 'file',
  theme: 'markdown',
  includeDeclarations: true,
  includeVersion: true,
  out: '.',
  disableOutputCheck: true,
  tsconfig: 'tsconfig.json',
  excludePrivate: true,
  excludeProtected: true,
  excludeExternals: true,
  stripInternal: true,
  readme: 'main.md',
  name: 'collection',
  ignoreCompilerErrors: true,
  hideGenerator: true,
  plugin: 'typedoc-plugin-markdown,@zimmed/typedoc-plugin-respect-name-tag',
  listInvalidSymbolLinks: true,
};
